### ISSUE TITLE
A type with two indexers cannot be compared

### ISSUE THREAD

**Issue by jsolt** [derekgreer/expectedObjects#15]
Example
```csharp
public class MultipleIndexMethodsType<T>
{
    readonly IList<T> _ints;

    public DoubleIndexType(IList<T> ints)
    {
        _ints = ints;
    }

    public T this[int index] => _ints[index];
    public T this[string index] => _ints[int.Parse(index)];

    public int Count => _ints.Count;
}

var actual = new MultipleIndexMethodsType<int>(new List<int>{});
var expected = new MultipleIndexMethodsType<int>(new List<int>{});

var result = expected.ToExpectedObject().Equals(actual); // this throws
```

with an exception that has a stack trace like this:
```
Result StackTrace:	
at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at ExpectedObjects.PropertyInfoExtensions.ExcludeHiddenProperties(IEnumerable`1 infos, Type originType)
   at ExpectedObjects.EqualityComparer.IsLeaf(Object expected)
   at ExpectedObjects.EqualityComparer.Compare(Object expected, Object actual, String member, IWriter writer)
   at ExpectedObjects.EqualityComparer.ReportEquality(Object expected, Object actual, String member)
   at ExpectedObjects.EqualityComparer.AreEqual(Object expected, Object actual, IWriter writer, Boolean ignoreTypeInformation)
   at ExpectedObjects.ExpectedObjectExtensions.Matches(ExpectedObject expected, Object actual)
Result Message:
System.InvalidOperationException: Sequence contains more than one matching element
```

**Comment by derekgreer** [comment]
Fixed in version [2.3.2](https://github.com/derekgreer/expectedObjects/releases/tag/v2.3.2)
